### ISSUE TITLE
Set custom metadata

### ISSUE THREAD

**Issue by dfibuch** [bestander/gulp-deploy-azure-cdn#3]
Thank you for this awesome module! This is more of a question than an issue but it might be helpful for others looking for the same thing.

Is there any way to set custom metadata for each file? I can see that we can set cacheControl, which forms the properties of the blob but you can also create custom metadata entries using tools like Azure Management Studio.

Here is what I mean:

I have set the cacheControl property http://puu.sh/kfyL2/3ec48d3a3f.png
I want to be able to enter a custom entry like this http://puu.sh/kfyN1/0330c86367.png

Hope this makes sense.

Thank you.

**Comment by bestander** [comment]
Yes, this needs some clarification.  
Did you see the `metadata` option in the settings?  
It is a key-value object that can specify not only cacheControl but any metadata. 
Though it works for all the files in the pipe. 
If you want to set it individually you could call the task multiple time per every file. 
This would not be optimal but would not require a change.
Otherwise a PR to the core task is welcome https://github.com/bestander/deploy-azure-cdn/blob/master/src/deploy-task.js

**Comment by dfibuch** [comment]
Ye I saw that metadata can be set and I have successfully done this. Doing it for all files is perfectly fine so no change is required there.

My problem is that when specifying the metadata you need to tell it what property to set it against and then specify the key-value pair and in my case I don't know what the property is.

However, now we have changed the way we are going to use the blobs and don't need custom metadata entries. Instead will be using the name of the file to identify exactly what it is and set all the data on there.

Feel free to close this.

**Comment by bestander** [comment]
щл
